Docs: k8s updates
fugue/regula pull request #210
Opened 2021-09-28 19:11 UTC by becki-at-luminal

This PR adds documentation for Kubernetes support.

TODO:

- Home
- About

2021-09-28 19:31 UTC, ameliafugue requested changes
I had one small comment, but other than that it lgtm

2021-09-28 19:31 UTC, ameliafugue commented on docs/src/usage.md
> +- The test Terraform, CloudFormation, or Kubernetes file
Should we say Kubernetes Manifest file instead of Kubernetes file?

2021-09-29 14:34 UTC, ameliafugue approved these changes
LGTM 🎉

2021-09-29 19:56 UTC, jason-fugue approved these changes

2021-09-29 20:02 UTC, curtis-fugue approved these changes
Thank you!

2021-09-29 20:05 UTC, merged